### ISSUE TITLE
oAuth2 server

### ISSUE THREAD

**Issue by garrs** [Tony133/Symfony3OAuth#1]
Hey. Do you have an example of implementing an oAuth2 server in symfony 3.3 using: https://github.com/bshaffer/oauth2-server-bundle
or
https://github.com/FriendsOfSymfony/FOSOAuthServerBundle ?

**Comment by Tony133** [comment]
Hi, I did not do it yet, but I was thinking of doing it soon, I did just the client part to start to understand how it worked. You've also seen this -> http://oauth2.thephpleague.com

tony133
